disabled_rules:
- file_length
function_body_length:
 - 100 # warning
 - 150 #error
identifier_name:
  excluded:
    - x
    - y
type_body_length:
  - 350 # warning
  - 400 # error
cyclomatic_complexity:
  - 15 # warning
  - 20 # error
line_length:
  warning: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
reporter: "xcode"

